name: Rebuild Algolia Index
push:
    branches:
      - master
steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.4' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
    - run: |
        gem install bundler
        bundle exec jekyll algolia